// frontend/src/components/dashboard/CategoryBreakdown.vue
<template>
  <div class="bg-white rounded-lg shadow">
    <div class="px-6 py-5">
      <h3 class="text-lg font-semibold mb-4">Category Breakdown</h3>
      
      <div v-if="loading" class="flex justify-center">
        <LoadingSpinner />
      </div>

      <div v-else class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Category
              </th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Amount
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr v-for="[category, amount] in sortedCategories" :key="category">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                {{ formatCategory(category) }}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-right text-red-600">
                ${{ amount.toFixed(2) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import LoadingSpinner from '../common/LoadingSpinner.vue';

const props = defineProps<{
  categoryTotals?: Record<string, number>;
  loading?: boolean;
}>();

const sortedCategories = computed(() => {
  if (!props.categoryTotals) return [];
  return Object.entries(props.categoryTotals)
    .sort((a, b) => b[1] - a[1]);
});

const formatCategory = (category: string) => {
  return category.charAt(0).toUpperCase() + category.slice(1);
};</script>

// frontend/src/components/dashboard/CategoryBreakdown.jsx
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import LoadingSpinner from '../common/LoadingSpinner';

interface CategoryBreakdownProps {
  categoryTotals: Record<string, number> | undefined;
  isLoading?: boolean;
}

const CategoryBreakdown: React.FC<CategoryBreakdownProps> = ({ 
  categoryTotals,
  isLoading 
}) => {
  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-6">
          <LoadingSpinner />
        </CardContent>
      </Card>
    );
  }

  const sortedCategories = Object.entries(categoryTotals || {})
    .sort((a, b) => b[1] - a[1]);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Category Breakdown</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b">
                <th className="text-left p-2 font-semibold">Category</th>
                <th className="text-right p-2 font-semibold">Amount</th>
              </tr>
            </thead>
            <tbody>
              {sortedCategories.map(([category, amount]) => (
                <tr key={category} className="border-b">
                  <td className="p-2 font-medium">
                    {category.charAt(0).toUpperCase() + category.slice(1)}
                  </td>
                  <td className="text-right p-2 text-red-600">
                    ${amount.toFixed(2)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
};

export default CategoryBreakdown;
