// frontend/src/components/dashboard/MonthlyOverview.jsx
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MonthData } from '../../types/transaction';
import LoadingSpinner from '../common/LoadingSpinner';

interface MonthlyOverviewProps {
  monthlyBreakdown: Record<string, MonthData> | undefined;
  isLoading?: boolean;
}

const MonthlyOverview: React.FC<MonthlyOverviewProps> = ({ 
  monthlyBreakdown,
  isLoading 
}) => {
  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-6">
          <LoadingSpinner />
        </CardContent>
      </Card>
    );
  }

  const sortedMonths = Object.entries(monthlyBreakdown || {})
    .sort((a, b) => b[0].localeCompare(a[0]));

  return (
    <Card>
      <CardHeader>
        <CardTitle>Monthly Overview</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b">
                <th className="text-left p-2 font-semibold">Month</th>
                <th className="text-right p-2 font-semibold">Income</th>
                <th className="text-right p-2 font-semibold">Expenses</th>
                <th className="text-right p-2 font-semibold">Balance</th>
              </tr>
            </thead>
            <tbody>
              {sortedMonths.map(([month, data]) => (
                <tr key={month} className="border-b">
                  <td className="p-2 font-medium">{month}</td>
                  <td className="text-right p-2 text-green-600">
                    ${data.income.toFixed(2)}
                  </td>
                  <td className="text-right p-2 text-red-600">
                    ${data.expenses.toFixed(2)}
                  </td>
                  <td className={`text-right p-2 ${data.balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                    ${data.balance.toFixed(2)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
};

export default MonthlyOverview;

// frontend/src/components/dashboard/MonthlyOverview.vue
<template>
  <div class="bg-white rounded-lg shadow">
    <div class="px-6 py-5">
      <h3 class="text-lg font-semibold mb-4">Monthly Overview</h3>
      
      <div v-if="loading" class="flex justify-center">
        <LoadingSpinner />
      </div>

      <div v-else class="overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Month
              </th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Income
              </th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Expenses
              </th>
              <th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Balance
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <tr v-for="[month, data] in sortedMonths" :key="month">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                {{ month }}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-right text-green-600">
                ₺{{ data.income.toFixed(2) }}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-right text-red-600">
                ₺{{ data.expenses.toFixed(2) }}
              </td>
              <td 
                class="px-6 py-4 whitespace-nowrap text-sm text-right"
                :class="data.balance >= 0 ? 'text-green-600' : 'text-red-600'"
              >
                ₺{{ data.balance.toFixed(2) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { MonthData } from '@/types/transaction';
import LoadingSpinner from '../common/LoadingSpinner.vue';

const props = defineProps<{
  monthlyBreakdown?: Record<string, MonthData>;
  loading?: boolean;
}>();

const sortedMonths = computed(() => {
  if (!props.monthlyBreakdown) return [];
  return Object.entries(props.monthlyBreakdown)
    .sort((a, b) => b[0].localeCompare(a[0]));
});</script>
