// frontend/src/components/dashboard/SummaryCards.vue
<template>
  <div v-if="loading">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div v-for="i in 3" :key="i" class="bg-white rounded-lg shadow p-6">
        <LoadingSpinner size="small" />
      </div>
    </div>
  </div>

  <div v-else class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <div
      v-for="card in cards"
      :key="card.title"
      class="bg-white rounded-lg shadow"
    >
      <div class="px-6 py-5">
        <h3 class="text-lg font-semibold">{{ card.title }}</h3>
        <p :class="['text-2xl font-bold mt-2', card.colorClass]">
          ${{ card.amount.toFixed(2) }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { Summary } from '@/types/transaction';
import LoadingSpinner from '../common/LoadingSpinner.vue';

const props = defineProps<{
  summary: Summary | null;
  loading?: boolean;
}>();

const cards = computed(() => {
  if (!props.summary) return [];

  return [
    {
      title: 'Total Income',
      amount: props.summary.totalIncome,
      colorClass: 'text-green-600'
    },
    {
      title: 'Total Expenses',
      amount: props.summary.totalExpenses,
      colorClass: 'text-red-600'
    },
    {
      title: 'Balance',
      amount: props.summary.remainingAmount,
      colorClass: props.summary.remainingAmount >= 0 ? 'text-green-600' : 'text-red-600'
    }
  ];
});</script>

// frontend/src/components/dashboard/SummaryCards.tsx
// src/components/dashboard/SummaryCards.tsx

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Summary } from '../../types/transaction';
import LoadingSpinner from '../common/LoadingSpinner';
import ErrorBoundary from '../common/ErrorBoundary';

interface SummaryCardsProps {
  summary: Summary | null;
  isLoading?: boolean;
}

const SummaryCards: React.FC<SummaryCardsProps> = ({ summary, isLoading }) => {
  if (isLoading) {
    return (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[1, 2, 3].map((i) => (
          <Card key={i}>
            <CardContent className="p-6">
              <LoadingSpinner size="small" />
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (!summary) {
    return null;
  }

  const cards = [
    {
      title: 'Total Income',
      amount: summary.totalIncome,
      color: 'text-green-600'
    },
    {
      title: 'Total Expenses',
      amount: summary.totalExpenses,
      color: 'text-red-600'
    },
    {
      title: 'Balance',
      amount: summary.remainingAmount,
      color: summary.remainingAmount >= 0 ? 'text-green-600' : 'text-red-600'
    }
  ];

  return (
    <ErrorBoundary>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {cards.map((card) => (
          <Card key={card.title}>
            <CardHeader>
              <CardTitle>{card.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className={`text-2xl font-bold ${card.color}`}>
                ${card.amount.toFixed(2)}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </ErrorBoundary>
  );
};

export default SummaryCards;
